import { Site } from '../types/site';

export const INITIAL_DEFAULT_SITES: Site[] = [
  {
    id: '1',
    name: '디지털교과서',
    url: 'https://dt.edunet.net',
    category: '오늘의 수업',
    image_url: null,
    image_type: 'emoji',
    emoji: '🏫',
    status: 'public',
    memo: '전 학년 디지털교과서 뷰어 및 멀티미디어 자료',
    sort_order: 1,
    created_at: new Date('2026-01-01T00:14:00.000Z').toISOString(),
    updated_at: new Date('2026-01-01T00:14:00.000Z').toISOString(),
  },
  {
    id: '2',
    name: 'EBS 초등',
    url: 'https://primary.ebs.co.kr',
    category: '오늘의 수업',
    image_url: null,
    image_type: 'emoji',
    emoji: '⭐',
    status: 'public',
    memo: 'EBS 만점왕 및 초등 교과 영상 시청',
    sort_order: 2,
    created_at: new Date('2026-01-01T00:13:00.000Z').toISOString(),
    updated_at: new Date('2026-01-01T00:13:00.000Z').toISOString(),
  },
  {
    id: '3',
    name: '엔트리 (Entry)',
    url: 'https://playentry.org',
    category: '오늘의 수업',
    image_url: null,
    image_type: 'emoji',
    emoji: '💻',
    status: 'public',
    memo: '초등 블록 코딩 실습 사이트',
    sort_order: 3,
    created_at: new Date('2026-01-01T00:12:00.000Z').toISOString(),
    updated_at: new Date('2026-01-01T00:12:00.000Z').toISOString(),
  },
  {
    id: '4',
    name: '국립국어원 표준국어대사전',
    url: 'https://stdict.korean.go.kr',
    category: '국어',
    image_url: null,
    image_type: 'emoji',
    emoji: '📖',
    status: 'public',
    memo: '낱말 뜻 찾기 및 맞춤법 검색용',
    sort_order: 4,
    created_at: new Date('2026-01-01T00:11:00.000Z').toISOString(),
    updated_at: new Date('2026-01-01T00:11:00.000Z').toISOString(),
  },
  {
    id: '5',
    name: '국립어린이청소년도서관',
    url: 'https://www.nlcy.go.kr',
    category: '국어',
    image_url: null,
    image_type: 'emoji',
    emoji: '📚',
    status: 'public',
    memo: '전자책 및 어린이 추천도서 읽기',
    sort_order: 5,
    created_at: new Date('2026-01-01T00:10:00.000Z').toISOString(),
    updated_at: new Date('2026-01-01T00:10:00.000Z').toISOString(),
  },
  {
    id: '6',
    name: '똑똑! 수학탐험대',
    url: 'https://www.toctocmath.kr',
    category: '수학',
    image_url: null,
    image_type: 'emoji',
    emoji: '🔢',
    status: 'public',
    memo: '교육부 초등 수학 인공지능 맞춤형 학습',
    sort_order: 6,
    created_at: new Date('2026-01-01T00:09:00.000Z').toISOString(),
    updated_at: new Date('2026-01-01T00:09:00.000Z').toISOString(),
  },
  {
    id: '7',
    name: '지오지브라 (GeoGebra)',
    url: 'https://www.geogebra.org',
    category: '수학',
    image_url: null,
    image_type: 'emoji',
    emoji: '📐',
    status: 'public',
    memo: '도형 및 각도 조작 시각화 도구',
    sort_order: 7,
    created_at: new Date('2026-01-01T00:08:00.000Z').toISOString(),
    updated_at: new Date('2026-01-01T00:08:00.000Z').toISOString(),
  },
  {
    id: '8',
    name: '구글 어스 (Google Earth)',
    url: 'https://earth.google.com',
    category: '사회',
    image_url: null,
    image_type: 'emoji',
    emoji: '🗺️',
    status: 'public',
    memo: '세계 여러 나라 지형 및 지구 3D 탐험',
    sort_order: 8,
    created_at: new Date('2026-01-01T00:07:00.000Z').toISOString(),
    updated_at: new Date('2026-01-01T00:07:00.000Z').toISOString(),
  },
  {
    id: '9',
    name: '국토정보플랫폼 지도',
    url: 'https://map.ngii.go.kr',
    category: '사회',
    image_url: null,
    image_type: 'emoji',
    emoji: '🧭',
    status: 'public',
    memo: '우리 고장 및 우리나라 백지도와 지리 정보',
    sort_order: 9,
    created_at: new Date('2026-01-01T00:06:00.000Z').toISOString(),
    updated_at: new Date('2026-01-01T00:06:00.000Z').toISOString(),
  },
  {
    id: '10',
    name: '사이언스올 (ScienceAll)',
    url: 'https://www.scienceall.com',
    category: '과학',
    image_url: null,
    image_type: 'emoji',
    emoji: '🔬',
    status: 'public',
    memo: '과학문화 포털 및 멀티미디어 실험 자료',
    sort_order: 10,
    created_at: new Date('2026-01-01T00:05:00.000Z').toISOString(),
    updated_at: new Date('2026-01-01T00:05:00.000Z').toISOString(),
  },
  {
    id: '11',
    name: '기상청 날씨누리',
    url: 'https://www.weather.go.kr',
    category: '과학',
    image_url: null,
    image_type: 'emoji',
    emoji: '🌤️',
    status: 'public',
    memo: '기온, 강수량, 위성 레이더 영상 관찰',
    sort_order: 11,
    created_at: new Date('2026-01-01T00:04:00.000Z').toISOString(),
    updated_at: new Date('2026-01-01T00:04:00.000Z').toISOString(),
  },
  {
    id: '12',
    name: '캔바 (Canva) 디자인',
    url: 'https://www.canva.com',
    category: '기타',
    image_url: null,
    image_type: 'emoji',
    emoji: '🎨',
    status: 'public',
    memo: '수업 결과물 포스터 및 카드뉴스 제작',
    sort_order: 12,
    created_at: new Date('2026-01-01T00:03:00.000Z').toISOString(),
    updated_at: new Date('2026-01-01T00:03:00.000Z').toISOString(),
  },
  {
    id: '13',
    name: '패들렛 (Padlet)',
    url: 'https://padlet.com',
    category: '기타',
    image_url: null,
    image_type: 'emoji',
    emoji: '📌',
    status: 'public',
    memo: '학생 의견 모으기 및 토론 게시판',
    sort_order: 13,
    created_at: new Date('2026-01-01T00:02:00.000Z').toISOString(),
    updated_at: new Date('2026-01-01T00:02:00.000Z').toISOString(),
  },
  {
    id: '14',
    name: '띵커벨 (ThinkerBell)',
    url: 'https://www.tkbell.co.kr',
    category: '기타',
    image_url: null,
    image_type: 'emoji',
    emoji: '🎯',
    status: 'public',
    memo: '수업 퀴즈 및 형성평가 활동',
    sort_order: 14,
    created_at: new Date('2026-01-01T00:01:00.000Z').toISOString(),
    updated_at: new Date('2026-01-01T00:01:00.000Z').toISOString(),
  }
];
